--- # Handler file to start HTTPD
- hosts: dev demo
  user: admin
  become: yes
  connection: ssh

  vars:
    pkgname: httpd

  tasks:
    - name: Install package
      action: yum name='{{pkgname}}' state=installed
      notify: restart '{{pkgname}}'

  handlers:
    - name: restart '{{pkgname}}'
      action: service name='{{pkgname}}' state=restarted
        
