#!/root/ansible/myansible/bin/ansible-playbook
- name: Installing WebServer
  hosts: dev demo
  user: admin
  become: yes
  
  tasks:
    - name: Ensure Apache is at the Latest Version
      yum:
        name: httpd
        state: latest
    - name: Ensure Apache is Running
      service:
        name: httpd
        state: started
